# Site settings
title: Felipe Caputo blog
description: > # this means to ignore newlines until "baseurl:"
  Ramblings of a computer scientist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fvcaputo.github.io/" # the base hostname & protocol for your site
twitter_username: fvcaputo
github_username: fvcaputo
youtube_link: UCh_nXt6yvZHSAXBb06hesdA
youtube_username: channel

# Build settings
markdown: kramdown
